import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link
              rel="stylesheet"
              href="https://unpkg.com/aos@next/dist/aos.css"
            />
      </head>
      <body className={inter.className}>
        <Header />
        {children}</body>
    </html>
  )
}
